Merge remote-tracking branch 'origin/main'
# Conflicts:
#	src/Dockerfile

diff --git a/.github/workflows/minikube.yaml b/.github/workflows/minikube.yaml
--- a/.github/workflows/minikube.yaml
+++ b/.github/workflows/minikube.yaml
@@ -75,12 +75,20 @@ jobs:
           sleep 10
           curl http://localhost:5001/todoitems || echo "Port-forwarding failed or application not responding"
 
+      - name: Populate Data Inside Pod
+        run: |
+          POD_NAME=$(kubectl get pods --selector=app.kubernetes.io/name=dotnet-todo --output=jsonpath="{.items[0].metadata.name}")
+          echo "Posting data to /todoitems endpoint inside pod $POD_NAME on port 8080"
+          kubectl exec $POD_NAME -- curl -s -X POST -H "Content-Type: application/json" \
+          -d '{"name":"walk dog","isComplete":false}' http://localhost:8080/todoitems || echo "POST /todoitems failed"
+
       - name: Test Application Inside Pod
         run: |
           POD_NAME=$(kubectl get pods --selector=app.kubernetes.io/name=dotnet-todo --output=jsonpath="{.items[0].metadata.name}")
           echo "Testing GET /todoitems endpoint inside pod $POD_NAME on port 8080"
           kubectl exec  $POD_NAME -- curl -s http://localhost:8080/todoitems || echo "GET /todoitems failed"
-          
+      
           echo "Testing GET /todoitems/1 endpoint inside pod $POD_NAME on port 8080"
           kubectl exec  $POD_NAME -- curl -s http://localhost:8080/todoitems/1 || echo "GET /todoitems/1 failed"
+
 
